function releaseCam
S.fh = figure('units','pixels',...
    'position',[200 200 200 100],...
    'menubar','none',...
    'name','releaseCam',...
    'numbertitle','off',...
    'resize','off');
S.text = uicontrol('style','text',...                                          %Creating Pulse Ox Title
    'unit','pix',...
    'position',[0 60 200 20],...
    'ForegroundColor','black',...
    'fontsize',14,'HorizontalAlignment','center',...
    'string','Select to Stop Video');
S.Stop = uicontrol('style','push',...
    'units','pix',...
    'position',[10 10 180 40],...
    'HorizontalAlign','left',...
    'string','Stop and Close',...
    'fontsize',10,'fontweight','bold',...
    'callback',{@stopandclose,S});

function stopandclose(varargin)   
close('releaseCam')%close the MainDisp Gui
evalin('base','release(vid)');
evalin('base','stop(ValRead)');
evalin('base','delete(ValRead)');
evalin('base','clear ValRead');
evalin('base','clear dp');
